<?php
$modulo_plataforma='Coaching';
require_once '../config/validaciones_seguridad.php';
require_once '../config/conexion_db.php';
require_once 'lib/coaching_seguridad.php';
require_once 'lib/coaching_acompanamiento.php';
$titulo_header='Coaching | Detalle acompañamiento';
$id=validar_input(base64_decode($_GET['reg']??'',true)?:'');$perfil=coachingPerfilUsuarioActual();
if(!$id||$perfil===null||!usuarioPuedeVerAcompanamiento($enlace_db,$id,$_SESSION['usu_id'],$perfil)){header('Location:../permiso_denegado.php');exit;}
$st=$enlace_db->prepare("SELECT A.*,U.`usu_nombres_apellidos` colaborador,U.`usu_id` documento,L.`usu_nombres_apellidos` lider,S.`gcsg_nombre` segmento,X.`gcas_nombre` accion,X.`gcas_codigo` accion_codigo FROM `tb_gestion_coaching_acompanamiento` A LEFT JOIN `tb_administrador_usuario` U ON U.`usu_id`=A.`gca_colaborador_id` LEFT JOIN `tb_administrador_usuario` L ON L.`usu_id`=A.`gca_lider_id` LEFT JOIN `tb_gestion_coaching_segmento` S ON S.`gcsg_id`=A.`gca_segmento_id` LEFT JOIN `tb_gestion_coaching_accion_seguimiento` X ON X.`gcas_id`=A.`gca_accion_id` WHERE A.`gca_id`=? LIMIT 1");$st->bind_param('s',$id);$st->execute();$a=$st->get_result()->fetch_assoc();
$si=$enlace_db->prepare("SELECT I.`gcis_categoria`,I.`gcis_nombre` FROM `tb_gestion_coaching_acompanamiento_indicador` R JOIN `tb_gestion_coaching_indicador_seguimiento` I ON I.`gcis_id`=R.`gcai_indicador_id` WHERE R.`gcai_acompanamiento_id`=? ORDER BY I.`gcis_categoria`,I.`gcis_orden`");$si->bind_param('s',$id);$si->execute();$inds=$si->get_result()->fetch_all(MYSQLI_ASSOC);
$se=$enlace_db->prepare("SELECT * FROM `tb_gestion_coaching_escalamiento` WHERE `gces_acompanamiento_id`=? LIMIT 1");$se->bind_param('s',$id);$se->execute();$esc=$se->get_result()->fetch_assoc();
$sh=$enlace_db->prepare("SELECT * FROM `tb_gestion_coaching_acompanamiento_historial` WHERE `gcah_acompanamiento_id`=? ORDER BY `gcah_registro_fecha` DESC");$sh->bind_param('s',$id);$sh->execute();$hist=$sh->get_result()->fetch_all(MYSQLI_ASSOC);
$meses=[1=>'Enero',2=>'Febrero',3=>'Marzo',4=>'Abril',5=>'Mayo',6=>'Junio',7=>'Julio',8=>'Agosto',9=>'Septiembre',10=>'Octubre',11=>'Noviembre',12=>'Diciembre'];
?>
<!DOCTYPE html><html lang="ES"><head><?php include '../config/configuracion_estilos.php'; ?><style>.card-title-bar{background:#176486;color:white;padding:8px 10px;font-weight:bold}.detail-card{background:white;border:1px solid #ddd;margin-bottom:12px}.detail-body{padding:12px}.label{font-size:10px;color:#666;text-transform:uppercase}.value{font-size:12px;white-space:pre-wrap}.timeline{border-left:2px solid #72bf44;padding-left:15px}.timeline-item{margin-bottom:12px}</style></head><body><?php include '../menu_principal.php';include '../menu_header.php'; ?><div class="contenido fondo-gris"><div class="container-fluid py-2">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="mb-0"><?php echo htmlspecialchars($a['gca_id']); ?> - <?php echo htmlspecialchars($a['accion']); ?></h5><div><a class="btn btn-corp" href="gestion_coaching_acompanamientos.php"><span class="fas fa-arrow-left"></span> Volver</a><?php if($a['gca_paquete_id']): ?><a class="btn btn-success ml-1" href="gestion_coaching_ver.php?reg=<?php echo base64_encode($a['gca_paquete_id']); ?>"><span class="fas fa-graduation-cap"></span> Ver paquete</a><?php endif; ?></div></div>
<div class="row"><div class="col-lg-8">
<div class="detail-card"><div class="card-title-bar">Datos de seguimiento</div><div class="detail-body"><div class="row"><div class="col-md-6 mb-2"><div class="label">Colaborador</div><div class="value"><?php echo htmlspecialchars($a['colaborador'].' - '.$a['documento']); ?></div></div><div class="col-md-6 mb-2"><div class="label">Líder</div><div class="value"><?php echo htmlspecialchars($a['lider']); ?></div></div><div class="col-md-4"><div class="label">Correo líder</div><div class="value"><?php echo htmlspecialchars($a['gca_correo_lider']); ?></div></div><div class="col-md-3"><div class="label">Segmento</div><div class="value"><?php echo htmlspecialchars($a['segmento']); ?></div></div><div class="col-md-2"><div class="label">Empresa</div><div class="value"><?php echo htmlspecialchars($a['gca_empresa']); ?></div></div><div class="col-md-3"><div class="label">Periodo</div><div class="value"><?php echo $meses[(int)$a['gca_mes']].' '.$a['gca_anio']; ?></div></div></div></div></div>
<div class="detail-card"><div class="card-title-bar">Indicadores objeto de seguimiento</div><div class="detail-body"><ul class="mb-0"><?php foreach($inds as $i): ?><li><strong><?php echo htmlspecialchars($i['gcis_categoria']); ?>:</strong> <?php echo htmlspecialchars($i['gcis_nombre']); ?></li><?php endforeach; ?></ul></div></div>
<div class="detail-card"><div class="card-title-bar">Reporte del proceso</div><div class="detail-body"><div class="label">Motivo - Justificación</div><div class="value mb-3"><?php echo nl2br(htmlspecialchars($a['gca_motivo_justificacion'])); ?></div><div class="label">Compromisos adquiridos</div><div class="value"><?php echo nl2br(htmlspecialchars($a['gca_compromisos_colaborador'])); ?></div></div></div>
<?php if($esc): ?><div class="detail-card"><div class="card-title-bar">Escalamiento</div><div class="detail-body"><div class="row"><div class="col-md-6"><div class="label">Asunto</div><div class="value"><?php echo htmlspecialchars($esc['gces_asunto_correo']); ?></div></div><div class="col-md-3"><div class="label">Fecha y hora</div><div class="value"><?php echo htmlspecialchars($esc['gces_fecha_hora_envio']); ?></div></div><div class="col-md-3"><div class="label">Destinatario</div><div class="value"><?php echo htmlspecialchars($esc['gces_destinatario_nombre']); ?></div></div></div></div></div><?php endif; ?>
</div><div class="col-lg-4"><div class="detail-card"><div class="card-title-bar">Trazabilidad</div><div class="detail-body timeline"><?php foreach($hist as $h): ?><div class="timeline-item"><strong><?php echo htmlspecialchars($h['gcah_accion']); ?></strong><div class="value"><?php echo htmlspecialchars($h['gcah_detalle']??''); ?></div><small><?php echo htmlspecialchars($h['gcah_registro_fecha'].' - '.$h['gcah_usuario']); ?></small></div><?php endforeach; ?></div></div></div></div>
</div></div><?php include '../footer.php';include '../config/configuracion_js.php'; ?></body></html>
